/**
 * Eden Park's grandstands measured from the LiDAR (core/edenPark.ts, generated by tools/hero/sites/eden_park.py; drawn by
 * world/scenery/aucklandSites.ts buildStadiums): matched to the OSM stands, profiles that rake down to the pitch, and the
 * LiDAR spot checks.
 */
import { describe, expect, it } from 'vitest';
import { AKL } from '../src/core/auckland';
import { EDEN_PARK_STANDS } from '../src/core/edenPark';
import { siteLayout } from '../src/world/scenery/aucklandSites';

describe('Eden Park stands (measured)', () => {
  it('four stands at Eden Park, each matching one of the OSM stands the scenery draws', () => {
    expect(EDEN_PARK_STANDS).toHaveLength(4);
    for (const s of EDEN_PARK_STANDS) expect(Math.hypot(s.x - AKL.eden_park.x, s.z - AKL.eden_park.z)).toBeLessThan(250);
    const stands = siteLayout()!.stadiums.flatMap((st) => st.stands);
    for (const s of EDEN_PARK_STANDS) {
      const near = stands.filter((r) => {
        let x = 0, z = 0;
        for (let i = 0; i < r.pts.length; i += 2) { x += r.pts[i]; z += r.pts[i + 1]; }
        return Math.hypot((x * 2) / r.pts.length - s.x, (z * 2) / r.pts.length - s.z) < 25;
      });
      expect(near.length, s.name).toBe(1);
    }
  });

  it('each stand falls to the pitch: its last strip is the lowest, its highest strip 10–35 m', () => {
    for (const s of EDEN_PARK_STANDS) {
      const hs = s.strips.map((t) => t.h);
      expect(hs[hs.length - 1]).toBe(Math.min(...hs));
      expect(Math.max(...hs)).toBeGreaterThan(10);
      expect(Math.max(...hs)).toBeLessThan(35);
    }
  });

  it('at the LiDAR heights: ≥ 90 % of the spot checks within ±2 m, all within ±3.5 m', () => {
    // (a strip that holds the canopy's front edge mixes two heights: the two such spots miss by ~3 m)
    let n = 0;
    let ok = 0;
    for (const s of EDEN_PARK_STANDS)
      for (const t of s.strips) {
        if (!t.spot) continue;
        const h = t.spot[2];
        const d = Math.abs(Math.max(h, 1.5) - t.h);
        expect(d).toBeLessThan(3.5);
        if (d < 2) ok++;
        n++;
      }
    expect(n).toBeGreaterThanOrEqual(24);
    expect(ok / n).toBeGreaterThanOrEqual(0.9);
  });
});
