/**
 * Auckland War Memorial Museum (core/museum.ts, generated by tools/hero/sites/museum.py; world/scenery/museum.ts):
 * where it stands, its LiDAR heights, the mesh and the sim's obstacle.
 */
import { describe, expect, it } from 'vitest';
import { Vector3 } from 'three';
import { AKL } from '../src/core/auckland';
import { MUSEUM_CENTRE, MUSEUM_COLUMNS, MUSEUM_OUTLINE, MUSEUM_PARTS, MUSEUM_SPOTS } from '../src/core/museum';
import { BuildingIndex, buildBuildingGeometry, pointInRing } from '../src/sim/buildings';
import { GeometryBuilder } from '../src/world/scenery/GeometryBuilder';
import { LightList } from '../src/world/scenery/builders';
import { buildMuseum } from '../src/world/scenery/museum';

const roofAt = (x: number, z: number) => Math.max(-Infinity, ...MUSEUM_PARTS.filter((p) => pointInRing(p.ring, x, z)).map((p) => p.h));

describe('Auckland War Memorial Museum (measured)', () => {
  it('stands on Pukekawa, its centre inside its OSM outline, near the Domain landmark, the portico to the north', () => {
    expect(pointInRing(MUSEUM_OUTLINE, MUSEUM_CENTRE.x, MUSEUM_CENTRE.z)).toBe(true);
    expect(Math.hypot(MUSEUM_CENTRE.x - AKL.domain.x, MUSEUM_CENTRE.z - AKL.domain.z)).toBeLessThan(150);
    // the portico's columns stand on the north front, just outside the walls' outline
    for (const [x, z] of MUSEUM_COLUMNS) {
      expect(z).toBeLessThan(MUSEUM_CENTRE.z - 40);
      expect(Math.abs(x - MUSEUM_CENTRE.x)).toBeLessThan(25);
    }
  });

  it('roofs at the LiDAR heights (spot checks ±2 m); the domes the highest parts, inner rings higher', () => {
    expect(MUSEUM_SPOTS.length).toBeGreaterThanOrEqual(2);
    for (const [x, z, h] of MUSEUM_SPOTS) expect(Math.abs(roofAt(x, z) - h)).toBeLessThan(2);
    const block = Math.max(...MUSEUM_PARTS.filter((p) => p.kind === 'block').map((p) => p.h));
    const domes = MUSEUM_PARTS.filter((p) => p.kind !== 'block');
    expect(domes.some((p) => p.kind === 'atrium')).toBe(true);
    expect(domes.some((p) => p.kind === 'dome')).toBe(true);
    expect(Math.max(...domes.map((p) => p.h))).toBeGreaterThanOrEqual(block - 1);
    // the building is ~20–30 m tall over the hill's crown, not the old 34 m box
    expect(Math.max(...MUSEUM_PARTS.map((p) => p.h))).toBeGreaterThan(22);
    expect(Math.max(...MUSEUM_PARTS.map((p) => p.h))).toBeLessThan(32);
    expect(MUSEUM_COLUMNS).toHaveLength(8);
  });

  it('builds one mesh with its columns and a floodlight', () => {
    const B = new GeometryBuilder();
    const L = new LightList();
    const g = buildMuseum(B, L, () => 70);
    expect(g).toBe(70);
    expect(B.triangleCount).toBeGreaterThan(300);
    expect(B.triangleCount).toBeLessThan(4000);
    expect(L.count).toBeGreaterThan(0);
  });

  it('the sim crashes into it and never collapses it', () => {
    const geo = buildBuildingGeometry(() => 70)!;
    const idx = new BuildingIndex(geo);
    const [x, z, h] = MUSEUM_SPOTS[0];
    const hit = idx.firstHit(new Vector3(x, 70 + h + 30, z), new Vector3(x, 70 + h - 3, z));
    expect(hit?.building.id).toBe(-100);
    expect(hit?.building.fixed).toBe(true);
    expect(idx.firstHit(new Vector3(x, 70 + 60, z), new Vector3(x, 70 + 35, z))).toBeNull();
  });
});
