/**
 * Westfield Newmarket (core/westfieldNewmarket.ts, generated by tools/hero/sites/westfield_port.py from the prototype's
 * model; world/scenery/westfieldNewmarket.ts): where it stands, its LiDAR heights, the mesh, the sim's obstacle and the
 * procedural Newmarket kept out of its footprint.
 */
import { describe, expect, it } from 'vitest';
import { Vector3 } from 'three';
import { geoToWorld } from '../src/core/auckland';
import { WESTFIELD_CENTRE, WESTFIELD_PRISMS, WESTFIELD_SPOTS } from '../src/core/westfieldNewmarket';
import { BuildingIndex, buildBuildingGeometry, pointInRing } from '../src/sim/buildings';
import { GeometryBuilder } from '../src/world/scenery/GeometryBuilder';
import { LightList } from '../src/world/scenery/builders';
import { buildWestfieldNewmarket, westfieldCovers } from '../src/world/scenery/westfieldNewmarket';

describe('Westfield Newmarket (measured)', () => {
  it('stands on Broadway, Newmarket', () => {
    // 277 Broadway (OSM): −36.8715, 174.7759
    const p = geoToWorld(-36.8715, 174.7759);
    expect(Math.hypot(WESTFIELD_CENTRE.x - p.x, WESTFIELD_CENTRE.z - p.z)).toBeLessThan(120);
    expect(WESTFIELD_PRISMS.length).toBeGreaterThanOrEqual(8); // the 8 OSM parts, plus the upper deck of 277's car park
  });

  it('roofs at the LiDAR heights: every spot check within ±2 m of the part over it', () => {
    expect(WESTFIELD_SPOTS.length).toBeGreaterThanOrEqual(6);
    let checked = 0;
    for (const [x, z, h] of WESTFIELD_SPOTS) {
      const over = WESTFIELD_PRISMS.filter((p) => pointInRing(p.ring, x, z));
      if (!over.length) continue;
      expect(Math.abs(Math.max(...over.map((p) => p.h)) - h)).toBeLessThan(2);
      checked++;
    }
    expect(checked).toBeGreaterThanOrEqual(5);
  });

  it('builds one mesh with its dome light; procedural Newmarket keeps out of the footprint', () => {
    const B = new GeometryBuilder();
    const L = new LightList();
    expect(buildWestfieldNewmarket(B, L, () => 60)).toBe(60);
    expect(B.triangleCount).toBeGreaterThan(300);
    expect(B.triangleCount).toBeLessThan(6000);
    expect(L.count).toBeGreaterThan(0);
    const [x, z] = WESTFIELD_SPOTS[0];
    expect(westfieldCovers(x, z)).toBe(true);
    expect(westfieldCovers(WESTFIELD_CENTRE.x + 600, WESTFIELD_CENTRE.z)).toBe(false);
  });

  it('the sim crashes into it and never collapses it', () => {
    const idx = new BuildingIndex(buildBuildingGeometry(() => 60)!);
    const [x, z, h] = WESTFIELD_SPOTS[0];
    const hit = idx.firstHit(new Vector3(x, 60 + h + 30, z), new Vector3(x, 60 + h - 3, z));
    expect(hit?.building.id).toBe(-101);
    expect(hit?.building.fixed).toBe(true);
  });
});
