/**
 * F35-A audio — what a radio call actually says (pure logic, unit-tested).
 *
 * A 'radio' event carries the subtitle text and a VoiceId hint. The fixed clips are generic
 * ("Bandits, bandits."), so playing the hint for a dynamic call ("two bandits, BRAA 045, 40 miles,
 * angels 25, hot") makes the voice disagree with the subtitle. resolveRadioSpeech() decides:
 *
 *  1. the hint clip, if its spoken words appear verbatim (in order) in the subtitle;
 *  2. for AWACS calls, the subtitle spoken word by word from short Piper segments (numbers,
 *     brevity words, callsigns) — words without a segment are left out, never replaced;
 *  3. otherwise nothing (the caller plays a key-up click + static burst: text-only call).
 *
 * So what is heard is always the subtitle or a subset of it, in the same order.
 */
import type { VoiceId } from '../../core/types';

/** Radio segments generated by tools/gen-voices.sh (not part of the VoiceId contract). */
export const SEGMENT_IDS = [
  's_0', 's_1', 's_2', 's_3', 's_4', 's_5', 's_6', 's_7', 's_8', 's_9',
  's_10', 's_11', 's_12', 's_13', 's_14', 's_15', 's_16', 's_17', 's_18', 's_19',
  's_20', 's_30', 's_40', 's_50', 's_60', 's_70', 's_80', 's_90',
  's_darkstar', 's_viper',
  's_single', 's_heavy', 's_group', 's_groups', 's_single_group',
  's_new_picture', 's_pop_up_group', 's_threat', 's_last_bandit',
  's_bandit', 's_bandits',
  's_braa', 's_bullseye', 's_miles', 's_angels', 's_track',
  's_hot', 's_cold', 's_flanking', 's_beaming',
  's_north', 's_northeast', 's_east', 's_southeast', 's_south', 's_southwest', 's_west', 's_northwest',
  's_wave', 's_destroyed', 's_raid_turning', 's_tail',
] as const;
export type SegmentId = (typeof SEGMENT_IDS)[number];
/** Any playable radio/Betty clip. */
export type ClipId = VoiceId | SegmentId;
/** A pause between two phrases of a composed call. */
export const PAUSE = ',';
export type SpeechToken = ClipId | typeof PAUSE;

/** Spoken words of every fixed clip (must match tools/gen-voices.sh — checked by a test). */
export const VOICE_TEXT: Record<VoiceId, string> = {
  b_missile: 'Missile. Missile.',
  b_pull_up: 'Pull up. Pull up.',
  b_altitude: 'Altitude. Altitude.',
  b_bingo: 'Bingo. Bingo.',
  b_fuel_low: 'Fuel low.',
  b_engine_fire: 'Engine fire. Engine fire.',
  b_warning: 'Warning. Warning.',
  b_over_g: 'Over G. Over G.',
  b_aoa: 'Angle of attack.',
  b_flares_low: 'Flares low.',
  b_chaff_low: 'Chaff low.',
  b_hydraulics: 'Hydraulics.',
  b_speed: 'Speed. Speed.',
  p_fox3: 'Fox three!',
  p_fox2: 'Fox two!',
  p_rifle: 'Rifle!',
  p_magnum: 'Magnum!',
  p_guns: 'Guns, guns!',
  p_splash: 'Splash one!',
  p_spike: 'Spike!',
  p_mud_spike: 'Mud spike!',
  p_defending: 'Defending!',
  p_winchester: 'Winchester.',
  p_bingo: 'Bingo fuel, R. T. B.',
  p_copy: 'Copy.',
  p_engaged: 'Engaged.',
  p_target_destroyed: 'Target destroyed.',
  a_bandits: 'Bandits, bandits.',
  a_new_picture: 'New picture. Multiple groups.',
  a_sam_launch: 'Sam launch! Sam launch!',
  a_good_kill: 'Good kill. Good kill.',
  a_mission_complete: 'Mission complete. Return to base.',
  a_mission_failed: 'Mission failed.',
  a_objective_complete: 'Objective complete.',
  a_rtb: 'Return to base.',
  a_eject: 'Eject! Eject!',
  a_friendly_down: 'Friendly down.',
};

/** Lower-case words, punctuation stripped, a few brevity abbreviations expanded. */
export function speechWords(text: string): string[] {
  const t = text
    .toLowerCase()
    .replace(/\br\.\s*t\.\s*b\.?/g, 'rtb')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\brtb\b/g, 'return to base')
    .trim();
  return t ? t.split(' ') : [];
}

/** Do the words of `clip` appear, in order and adjacent, in `words`? */
function containsRun(words: readonly string[], clip: readonly string[]): boolean {
  if (!clip.length) return false;
  outer: for (let i = 0; i + clip.length <= words.length; i++) {
    for (let j = 0; j < clip.length; j++) if (words[i + j] !== clip[j]) continue outer;
    return true;
  }
  return false;
}

/** Does the fixed clip say exactly (a contiguous part of) what the subtitle says? */
export function clipMatchesText(id: VoiceId, text: string): boolean {
  return containsRun(speechWords(text), speechWords(VOICE_TEXT[id]));
}

const PHRASES: readonly (readonly [string, SegmentId])[] = [
  ['the raid is turning back good work', 's_raid_turning'],
  ['single group', 's_single_group'],
  ['new picture', 's_new_picture'],
  ['pop up group', 's_pop_up_group'],
  ['last bandit', 's_last_bandit'],
];
const PHRASE_WORDS = PHRASES.map(([p, id]) => [p.split(' '), id] as const);

const WORDS: Record<string, SegmentId> = {
  darkstar: 's_darkstar', viper: 's_viper',
  single: 's_single', heavy: 's_heavy', group: 's_group', groups: 's_groups', threat: 's_threat',
  bandit: 's_bandit', bandits: 's_bandits',
  braa: 's_braa', bullseye: 's_bullseye', miles: 's_miles', angels: 's_angels', track: 's_track',
  hot: 's_hot', cold: 's_cold', flanking: 's_flanking', beaming: 's_beaming',
  north: 's_north', northeast: 's_northeast', east: 's_east', southeast: 's_southeast',
  south: 's_south', southwest: 's_southwest', west: 's_west', northwest: 's_northwest',
  wave: 's_wave', destroyed: 's_destroyed',
  zero: 's_0', one: 's_1', two: 's_2', three: 's_3', four: 's_4', five: 's_5', six: 's_6', seven: 's_7', eight: 's_8',
};

function digitId(d: number): SegmentId {
  return `s_${d}` as SegmentId;
}

/** Push the spoken form of a number: bearings digit by digit, 0–99 as words, larger digit by digit. */
function pushNumber(out: SpeechToken[], digits: string, digitWise: boolean): void {
  const n = Number(digits);
  if (digitWise || n > 99) {
    for (const c of digits) out.push(digitId(Number(c)));
    return;
  }
  if (n < 20) out.push(`s_${n}` as SegmentId);
  else {
    out.push(`s_${Math.floor(n / 10) * 10}` as SegmentId);
    if (n % 10) out.push(digitId(n % 10));
  }
}

/**
 * The subtitle spoken with AWACS segments (PAUSE at each comma / full stop). Words without a
 * segment are skipped. Returns the token list and how many subtitle words it covered.
 */
export function composeAwacs(text: string): { tokens: SpeechToken[]; covered: number; total: number } {
  const tokens: SpeechToken[] = [];
  let covered = 0;
  let total = 0;
  // phrases are split at punctuation that marks a pause
  // (multi-sentence segments are joined first so their phrase is matched whole)
  const chunks = text.replace(/turning back[!.,]\s*good work/gi, 'turning back good work').split(/[,.!?:;…—]+/);
  for (const chunk of chunks) {
    const w = speechWords(chunk);
    if (!w.length) continue;
    if (tokens.length && tokens[tokens.length - 1] !== PAUSE) tokens.push(PAUSE);
    total += w.length;
    let i = 0;
    while (i < w.length) {
      let matched = false;
      for (const [pw, id] of PHRASE_WORDS) {
        if (i + pw.length > w.length) continue;
        let ok = true;
        for (let j = 0; j < pw.length && ok; j++) ok = w[i + j] === pw[j];
        if (ok) {
          tokens.push(id);
          covered += pw.length;
          i += pw.length;
          matched = true;
          break;
        }
      }
      if (matched) continue;
      const word = w[i];
      if (/^\d+$/.test(word)) {
        const prev = i > 0 ? w[i - 1] : '';
        pushNumber(tokens, word, word.length === 3 && (prev === 'braa' || prev === 'bullseye'));
        covered++;
      } else if (WORDS[word]) {
        tokens.push(WORDS[word]);
        covered++;
      }
      i++;
    }
  }
  while (tokens.length && tokens[tokens.length - 1] === PAUSE) tokens.pop();
  return { tokens, covered, total };
}

/** Minimum share of the subtitle's words a composed call must speak (else: text-only call). */
const MIN_COVERAGE = 0.6;

/**
 * What to play for a radio call. `null` = text-only (click + static).
 * The returned array is new (radio calls are rare events, not per frame).
 */
export function resolveRadioSpeech(text: string | undefined, voice: VoiceId | undefined): SpeechToken[] | null {
  if (!voice) return null;
  if (!text) return [voice];
  if (clipMatchesText(voice, text)) return [voice];
  if (voice.startsWith('a_')) {
    const c = composeAwacs(text);
    if (c.tokens.length >= 2 && c.covered >= MIN_COVERAGE * c.total) return c.tokens;
  }
  return null;
}

/** Spoken words of a token list (for tests / logs). */
export function spokenText(tokens: readonly SpeechToken[], segmentText: (id: SegmentId) => string): string {
  const parts: string[] = [];
  for (const t of tokens) {
    if (t === PAUSE) continue;
    if ((VOICE_TEXT as Record<string, string>)[t]) parts.push(VOICE_TEXT[t as VoiceId]);
    else parts.push(segmentText(t as SegmentId));
  }
  return parts.join(' ');
}
