/**
 * F35-A — AUDIO module entry point (`createAudio`, implements AudioApi).
 *
 * Everything is synthesised with Web Audio at runtime except the voice clips
 * (public/audio/voice/*.mp3, generated by tools/gen-voices.sh).
 *
 *  core/     AudioContext lifecycle & unlock (AudioEngine), mixer buses + compressor/limiter,
 *            one-shot pool, listener/spatialiser, procedural buffers, smoothed params
 *  synth/    voices (jet engine, rocket motor, gun, cockpit ambience, warning tones) and
 *            one-shot recipes (explosions, launches, impacts, clicks, chimes, breathing…)
 *  world/    game-facing managers: which aircraft/missiles/guns are heard, speed-of-sound
 *            delays, event → sound mapping
 *  voice/    clip loading, Betty scheduling, radio queue, playback with ducking, situational
 *            pilot callouts (spike / mud spike / bingo) and "missile defeated" detection
 *  music/    procedural soundtrack: menu theme, adaptive mission layer, stingers
 *
 * Game contract: unlock() on the first tap (we also self-unlock on any later gesture — e.g.
 * ?autostart=1), load() in the background, update(ctx) every frame, setPaused / stopAll /
 * setVolumes / playVoice / uiClick. Nothing here throws into the game loop.
 */
import type { AudioApi, CreateAudio, FrameContext } from '../core/contracts';
import type { EventBus, GameEventMap, GameEventName } from '../core/events';
import type { VoiceId } from '../core/types';
import { AudioEngine } from './core/AudioEngine';
import { createSynthBuffers } from './core/buffers';
import { Listener } from './core/Listener';
import { Mixer } from './core/Mixer';
import { OneShotPool } from './core/OneShots';
import type { SynthEnv } from './synth/build';
import { Music, type MusicMode } from './music/Music';
import { missileDefeated, uiClick } from './synth/recipes';
import { CalloutTracker, DefeatTracker } from './voice/callouts';
import { VoiceBank } from './voice/VoiceBank';
import { VoicePlayer } from './voice/VoicePlayer';
import { SessionSounds } from './world/SessionSounds';

const POOL_SIZE = { low: 10, medium: 16, high: 22 } as const;

interface Core {
  env: SynthEnv;
  voice: VoicePlayer;
  music: Music;
}

/** Wall-clock ms without a live mission frame after which the music returns to the menu theme. */
const MENU_AFTER_MS = 3000;

export class AudioSystem implements AudioApi {
  readonly engine = new AudioEngine();
  readonly bank = new VoiceBank();
  readonly listener = new Listener();
  core: Core | null = null;
  session: SessionSounds | null = null;
  private lastCtx: FrameContext | null = null;
  private apiPaused = false;
  private muted = false;
  private volumes = { master: 0.9, sfx: 0.9, voice: 1 };
  private readonly unsubs: (() => void)[] = [];
  /** Consecutive failing frames; audio disables itself after too many (never breaks the game). */
  private errors = 0;
  private failed = false;
  /** Diagnostics for tests / harnesses (counts of feedback cues played). */
  readonly stats = { defeated: 0, kills: 0, stingers: 0, callouts: 0 };
  private readonly callouts = new CalloutTracker();
  private readonly defeats = new DefeatTracker();
  private readonly incomingIds = new Int32Array(16);
  /** performance.now() of the last live (unpaused) mission frame. */
  private lastMissionWall = -1e9;

  constructor(private readonly events: EventBus) {
    this.engine.onReady((ctx) => this.initCore(ctx));
    this.bindEvents();
  }

  /* ───────────────────────── AudioApi ───────────────────────── */

  unlock(): Promise<void> {
    return this.engine.unlock().catch(() => undefined);
  }

  load(onProgress?: (fraction: number) => void): Promise<void> {
    return this.bank.load(onProgress).catch(() => undefined);
  }

  update(ctx: FrameContext): void {
    this.lastCtx = ctx;
    const core = this.core;
    if (!core || this.failed || !this.engine.running) return;
    try {
      const paused = this.apiPaused || ctx.paused;
      this.setMuted(paused);
      if (paused || !ctx.world || !ctx.camera) return;
      const env = core.env;
      const now = env.ctx.currentTime;
      const q = ctx.quality?.level ?? 'medium';
      if (!this.session || this.session.quality !== q) {
        this.session?.dispose();
        env.pool.max = POOL_SIZE[q];
        env.mixer.enableReverb(q === 'high');
        this.session = new SessionSounds(env, q);
      }
      this.listener.update(ctx);
      this.session.update(now, ctx.dt, ctx, this.listener);
      const p = ctx.player;
      const voice = core.voice;
      voice.update(ctx.dt, p && p.alive ? p.warnings : null);
      this.lastMissionWall = performance.now();
      this.updateCombatCues(core, now, ctx);
      env.pool.prune(now);
      this.errors = 0;
    } catch (err) {
      // never take the game loop down because of audio
      if (this.errors++ === 0) console.error('[audio] update failed', err);
      if (this.errors > 30) {
        this.failed = true;
        console.error('[audio] repeated failures — audio disabled');
        this.stopAll();
      }
    }
  }

  /**
   * Situational feedback that needs the player state: spike / mud-spike calls, the
   * "missile defeated" cue, music tension and music ducking. No allocations.
   */
  private updateCombatCues(core: Core, now: number, ctx: FrameContext): void {
    const p = ctx.player;
    const voice = core.voice;
    const alive = !!p && p.alive;
    let air = false;
    let ground = false;
    let launch = false;
    let n = 0;
    if (p && alive) {
      for (let i = 0; i < p.rwr.length; i++) {
        const c = p.rwr[i];
        if (c.state === 'launch') launch = true;
        if (c.state !== 'track' && c.state !== 'launch') continue;
        if (c.kind === 'sam' || c.kind === 'aaa') ground = true;
        else if (c.kind !== 'ewr' && c.kind !== 'awacs') air = true;
      }
      n = Math.min(p.incoming.length, this.incomingIds.length);
      for (let i = 0; i < n; i++) this.incomingIds[i] = p.incoming[i].missileId;
    }
    const call = this.callouts.update(voice.clock, air, ground);
    if (call && voice.radio.push(call, 1, voice.clock)) this.stats.callouts++;
    if (this.defeats.update(voice.clock, this.incomingIds, n, alive)) {
      missileDefeated(core.env, now + 0.02);
      this.stats.defeated++;
    }

    // music: tension from the threat picture
    let target = 0;
    if (n > 0 || launch) target = 1;
    else if (ground || air || (p && p.radar.lockedId != null)) target = 0.5;
    core.music.tension.update(voice.clock, target);
    core.env.mixer.setMusicDuck(voice.speaking ? 0.4 : n > 0 ? 0.6 : 1);
  }

  private musicMode(): MusicMode {
    if (this.failed) return 'off';
    if (this.apiPaused || performance.now() - this.lastMissionWall > MENU_AFTER_MS) return 'menu';
    return 'mission';
  }

  setVolumes(master: number, sfx: number, voice: number): void {
    this.volumes = { master, sfx, voice };
    this.core?.env.mixer.setVolumes(master, sfx, voice);
  }

  setPaused(paused: boolean): void {
    this.apiPaused = paused;
    this.setMuted(paused);
  }

  playVoice(id: VoiceId): void {
    try {
      this.core?.voice.play(id);
    } catch {
      /* ignore */
    }
  }

  uiClick(): void {
    // UI clicks come from user gestures: a good moment to (re)unlock
    void this.engine.unlock();
    const core = this.core;
    if (!core || !this.engine.running) return;
    try {
      uiClick(core.env, core.env.ctx.currentTime + 0.002);
    } catch {
      /* ignore */
    }
  }

  stopAll(): void {
    this.lastCtx = null;
    const core = this.core;
    if (!core) return;
    try {
      const now = core.env.ctx.currentTime;
      this.session?.silence(now);
      this.session?.dispose();
      this.session = null;
      core.env.pool.stopAll();
      core.voice.stopAll(true);
      core.env.mixer.setMusicDuck(1);
      this.callouts.reset();
      this.defeats.reset();
      this.lastMissionWall = -1e9;
    } catch (err) {
      console.error('[audio] stopAll', err);
    }
  }

  dispose(): void {
    for (const u of this.unsubs.splice(0)) u();
    this.stopAll();
    this.core?.music.dispose();
    this.core?.env.mixer.dispose();
    this.core = null;
    this.engine.dispose();
  }

  /* ───────────────────────── internals ───────────────────────── */

  private initCore(ctx: AudioContext): void {
    const mixer = new Mixer(ctx);
    mixer.setVolumes(this.volumes.master, this.volumes.sfx, this.volumes.voice);
    const buffers = createSynthBuffers(ctx);
    const pool = new OneShotPool(ctx, POOL_SIZE.medium, () => mixer.reverbSend);
    const env: SynthEnv = { ctx, mixer, buffers, pool };
    const music = new Music(env);
    this.core = { env, voice: new VoicePlayer(env, this.bank), music };
    music.resolveMode = () => this.musicMode();
    try {
      music.start();
    } catch (err) {
      console.error('[audio] music', err);
    }
    this.bank.attach(ctx);
    this.muted = false;
    this.setMuted(this.apiPaused);
  }

  private setMuted(muted: boolean): void {
    const core = this.core;
    if (!core || muted === this.muted) return;
    this.muted = muted;
    core.env.mixer.setMissionMuted(muted);
    if (muted) {
      const now = core.env.ctx.currentTime;
      core.voice.stopAll(false);
      this.session?.silence(now);
    }
  }

  /** Session + listener are live (a mission frame has been processed and we are not paused). */
  private live(): { s: SessionSounds; ctx: FrameContext } | null {
    const s = this.session;
    const ctx = this.lastCtx;
    if (!s || !ctx || !ctx.world || this.muted || this.failed || !this.engine.running || !this.listener.valid) return null;
    return { s, ctx };
  }

  private on<K extends GameEventName>(name: K, fn: (e: GameEventMap[K]) => void): void {
    this.unsubs.push(
      this.events.on(name, (e) => {
        try {
          fn(e);
        } catch (err) {
          console.error(`[audio] ${name}`, err);
        }
      }),
    );
  }

  private bindEvents(): void {
    const L = this.listener;
    const pid = (ctx: FrameContext) => ctx.player?.id ?? -1;

    this.on('explosion', (e) => {
      const l = this.live();
      if (l) l.s.impacts.onExplosion(e, l.ctx, L);
    });
    this.on('munition:launch', (e) => {
      const l = this.live();
      if (!l) return;
      l.s.weapons.onLaunch(e, l.ctx, L);
      l.s.impacts.onLaunch(e, l.ctx, L);
    });
    this.on('gun:state', (e) => {
      const l = this.live();
      if (l) l.s.weapons.onGunState(e, l.ctx, L);
    });
    this.on('gun:impact', (e) => {
      const l = this.live();
      if (l) l.s.impacts.onGunImpact(e, l.ctx, L);
    });
    this.on('player:hit', (e) => {
      const l = this.live();
      if (l) l.s.impacts.onPlayerHit(e, l.ctx, L);
    });
    this.on('countermeasure', (e) => {
      const l = this.live();
      if (l) l.s.weapons.onCountermeasure(e, l.ctx, L);
    });
    this.on('transonic', (e) => {
      const l = this.live();
      if (l) l.s.impacts.onTransonic(e, l.ctx, L);
    });
    this.on('rwr:new', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onRwrNew(e);
    });
    this.on('lock', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onLock(e, pid(l.ctx));
    });
    this.on('designate', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onDesignate(e, pid(l.ctx));
    });
    this.on('weapon:select', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onWeaponSelect(e, pid(l.ctx));
    });
    this.on('weapon:denied', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onDenied(e, pid(l.ctx));
    });
    this.on('warning', (e) => {
      const l = this.live();
      if (!l || !this.core) return;
      const v = this.core.voice;
      v.onWarning(e.id, e.active);
      if (e.id === 'bingo' && e.active) {
        // pilot calls it, DARKSTAR acknowledges
        const call = this.callouts.onBingo(v.clock);
        if (call) {
          v.radio.push(call, 1, v.clock);
          v.radio.push('a_rtb', 1, v.clock + 0.01);
        }
      }
    });
    this.on('munition:end', (e) => {
      const l = this.live();
      if (!l || !this.core || e.targetId == null || e.targetId !== pid(l.ctx)) return;
      if (this.defeats.onEnd(e.missile.id, e.reason)) {
        missileDefeated(this.core.env, this.core.env.ctx.currentTime + 0.02);
        this.stats.defeated++;
      }
    });
    this.on('player:hit', () => this.defeats.onPlayerHit());
    this.on('destroyed', (e) => {
      const l = this.live();
      if (!l || !this.core) return;
      const p = l.ctx.player;
      if (!p || e.attackerId !== p.id || e.entity.team === p.team) return;
      this.core.music.stinger('kill', 0.35);
      this.stats.kills++;
    });
    this.on('mission:end', (e) => {
      const core = this.core;
      if (!core || this.failed) return;
      core.music.stinger(e.success ? 'win' : 'fail', 0.3);
      this.stats.stingers++;
      if (e.success) core.voice.radio.push('p_copy', 1, core.voice.clock);
    });
    this.on('radio', (e) => {
      const l = this.live();
      if (!l || !this.core || e.team === 'red') return;
      this.core.voice.onRadio(e.voice, e.priority ?? 1);
    });
  }
}

/** Factory used by src/game/Game.ts. */
export const createAudio: CreateAudio = (events) => new AudioSystem(events);
