/**
 * F35-A — AUDIO module entry point (`createAudio`, implements AudioApi).
 *
 * Everything is synthesised with Web Audio at runtime except the voice clips
 * (public/audio/voice/*.mp3, generated by tools/gen-voices.sh).
 *
 *  core/     AudioContext lifecycle & unlock (AudioEngine), mixer buses + compressor/limiter,
 *            one-shot pool, listener/spatialiser, procedural buffers, smoothed params
 *  synth/    voices (jet engine, rocket motor, gun, cockpit ambience, warning tones) and
 *            one-shot recipes (explosions, launches, impacts, clicks, chimes, breathing…)
 *  world/    game-facing managers: which aircraft/missiles/guns are heard, speed-of-sound
 *            delays, event → sound mapping
 *  voice/    clip loading, Betty scheduling, radio queue, playback with ducking
 *
 * Game contract: unlock() on the first tap (we also self-unlock on any later gesture — e.g.
 * ?autostart=1), load() in the background, update(ctx) every frame, setPaused / stopAll /
 * setVolumes / playVoice / uiClick. Nothing here throws into the game loop.
 */
import type { AudioApi, CreateAudio, FrameContext } from '../core/contracts';
import type { EventBus, GameEventMap, GameEventName } from '../core/events';
import type { VoiceId } from '../core/types';
import { AudioEngine } from './core/AudioEngine';
import { createSynthBuffers } from './core/buffers';
import { Listener } from './core/Listener';
import { Mixer } from './core/Mixer';
import { OneShotPool } from './core/OneShots';
import type { SynthEnv } from './synth/build';
import { uiClick } from './synth/recipes';
import { VoiceBank } from './voice/VoiceBank';
import { VoicePlayer } from './voice/VoicePlayer';
import { SessionSounds } from './world/SessionSounds';

const POOL_SIZE = { low: 10, medium: 16, high: 22 } as const;

interface Core {
  env: SynthEnv;
  voice: VoicePlayer;
}

export class AudioSystem implements AudioApi {
  readonly engine = new AudioEngine();
  readonly bank = new VoiceBank();
  readonly listener = new Listener();
  core: Core | null = null;
  session: SessionSounds | null = null;
  private lastCtx: FrameContext | null = null;
  private apiPaused = false;
  private muted = false;
  private volumes = { master: 0.9, sfx: 0.9, voice: 1 };
  private readonly unsubs: (() => void)[] = [];
  /** Consecutive failing frames; audio disables itself after too many (never breaks the game). */
  private errors = 0;
  private failed = false;

  constructor(private readonly events: EventBus) {
    this.engine.onReady((ctx) => this.initCore(ctx));
    this.bindEvents();
  }

  /* ───────────────────────── AudioApi ───────────────────────── */

  unlock(): Promise<void> {
    return this.engine.unlock().catch(() => undefined);
  }

  load(onProgress?: (fraction: number) => void): Promise<void> {
    return this.bank.load(onProgress).catch(() => undefined);
  }

  update(ctx: FrameContext): void {
    this.lastCtx = ctx;
    const core = this.core;
    if (!core || this.failed || !this.engine.running) return;
    try {
      const paused = this.apiPaused || ctx.paused;
      this.setMuted(paused);
      if (paused || !ctx.world || !ctx.camera) return;
      const env = core.env;
      const now = env.ctx.currentTime;
      const q = ctx.quality?.level ?? 'medium';
      if (!this.session || this.session.quality !== q) {
        this.session?.dispose();
        env.pool.max = POOL_SIZE[q];
        env.mixer.enableReverb(q === 'high');
        this.session = new SessionSounds(env, q);
      }
      this.listener.update(ctx);
      this.session.update(now, ctx.dt, ctx, this.listener);
      const p = ctx.player;
      core.voice.update(ctx.dt, p && p.alive ? p.warnings : null);
      env.pool.prune(now);
      this.errors = 0;
    } catch (err) {
      // never take the game loop down because of audio
      if (this.errors++ === 0) console.error('[audio] update failed', err);
      if (this.errors > 30) {
        this.failed = true;
        console.error('[audio] repeated failures — audio disabled');
        this.stopAll();
      }
    }
  }

  setVolumes(master: number, sfx: number, voice: number): void {
    this.volumes = { master, sfx, voice };
    this.core?.env.mixer.setVolumes(master, sfx, voice);
  }

  setPaused(paused: boolean): void {
    this.apiPaused = paused;
    this.setMuted(paused);
  }

  playVoice(id: VoiceId): void {
    try {
      this.core?.voice.play(id);
    } catch {
      /* ignore */
    }
  }

  uiClick(): void {
    // UI clicks come from user gestures: a good moment to (re)unlock
    void this.engine.unlock();
    const core = this.core;
    if (!core || !this.engine.running) return;
    try {
      uiClick(core.env, core.env.ctx.currentTime + 0.002);
    } catch {
      /* ignore */
    }
  }

  stopAll(): void {
    this.lastCtx = null;
    const core = this.core;
    if (!core) return;
    try {
      const now = core.env.ctx.currentTime;
      this.session?.silence(now);
      this.session?.dispose();
      this.session = null;
      core.env.pool.stopAll();
      core.voice.stopAll(true);
    } catch (err) {
      console.error('[audio] stopAll', err);
    }
  }

  dispose(): void {
    for (const u of this.unsubs.splice(0)) u();
    this.stopAll();
    this.core?.env.mixer.dispose();
    this.core = null;
    this.engine.dispose();
  }

  /* ───────────────────────── internals ───────────────────────── */

  private initCore(ctx: AudioContext): void {
    const mixer = new Mixer(ctx);
    mixer.setVolumes(this.volumes.master, this.volumes.sfx, this.volumes.voice);
    const buffers = createSynthBuffers(ctx);
    const pool = new OneShotPool(ctx, POOL_SIZE.medium, () => mixer.reverbSend);
    const env: SynthEnv = { ctx, mixer, buffers, pool };
    this.core = { env, voice: new VoicePlayer(env, this.bank) };
    this.bank.attach(ctx);
    this.muted = false;
    this.setMuted(this.apiPaused);
  }

  private setMuted(muted: boolean): void {
    const core = this.core;
    if (!core || muted === this.muted) return;
    this.muted = muted;
    core.env.mixer.setMissionMuted(muted);
    if (muted) {
      const now = core.env.ctx.currentTime;
      core.voice.stopAll(false);
      this.session?.silence(now);
    }
  }

  /** Session + listener are live (a mission frame has been processed and we are not paused). */
  private live(): { s: SessionSounds; ctx: FrameContext } | null {
    const s = this.session;
    const ctx = this.lastCtx;
    if (!s || !ctx || !ctx.world || this.muted || this.failed || !this.engine.running || !this.listener.valid) return null;
    return { s, ctx };
  }

  private on<K extends GameEventName>(name: K, fn: (e: GameEventMap[K]) => void): void {
    this.unsubs.push(
      this.events.on(name, (e) => {
        try {
          fn(e);
        } catch (err) {
          console.error(`[audio] ${name}`, err);
        }
      }),
    );
  }

  private bindEvents(): void {
    const L = this.listener;
    const pid = (ctx: FrameContext) => ctx.player?.id ?? -1;

    this.on('explosion', (e) => {
      const l = this.live();
      if (l) l.s.impacts.onExplosion(e, l.ctx, L);
    });
    this.on('munition:launch', (e) => {
      const l = this.live();
      if (!l) return;
      l.s.weapons.onLaunch(e, l.ctx, L);
      l.s.impacts.onLaunch(e, l.ctx, L);
    });
    this.on('gun:state', (e) => {
      const l = this.live();
      if (l) l.s.weapons.onGunState(e, l.ctx, L);
    });
    this.on('gun:impact', (e) => {
      const l = this.live();
      if (l) l.s.impacts.onGunImpact(e, l.ctx, L);
    });
    this.on('player:hit', (e) => {
      const l = this.live();
      if (l) l.s.impacts.onPlayerHit(e, l.ctx, L);
    });
    this.on('countermeasure', (e) => {
      const l = this.live();
      if (l) l.s.weapons.onCountermeasure(e, l.ctx, L);
    });
    this.on('transonic', (e) => {
      const l = this.live();
      if (l) l.s.impacts.onTransonic(e, l.ctx, L);
    });
    this.on('rwr:new', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onRwrNew(e);
    });
    this.on('lock', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onLock(e, pid(l.ctx));
    });
    this.on('designate', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onDesignate(e, pid(l.ctx));
    });
    this.on('weapon:select', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onWeaponSelect(e, pid(l.ctx));
    });
    this.on('weapon:denied', (e) => {
      const l = this.live();
      if (l) l.s.avionics.onDenied(e, pid(l.ctx));
    });
    this.on('warning', (e) => {
      const l = this.live();
      if (l && this.core) this.core.voice.onWarning(e.id, e.active);
    });
    this.on('radio', (e) => {
      const l = this.live();
      if (!l || !this.core || e.team === 'red') return;
      this.core.voice.onRadio(e.voice, e.priority ?? 1);
    });
  }
}

/** Factory used by src/game/Game.ts. */
export const createAudio: CreateAudio = (events) => new AudioSystem(events);
