/**
 * F35-A — the CBD tower kit (issue #156): every Auckland CBD building taller than Scene 3 (30 Beach Rd, 49.6 m) as
 * terraces traced from the LINZ 2024 LiDAR — podium, shaft and setbacks, a crown, sloped (wedge) roofs, roof plant and
 * spires — replacing the one- or two-height LINZ blocks the CBD extrudes (aucklandBuildings.ts applyHeroBuildings).
 * The scenery gives each tower its facade (world/scenery/auckland.ts), the sim collides with the same prisms.
 *
 * The data (core/cbdTowersData.ts) is generated by tools/hero/sites/cbd_towers.py: the LiDAR height above ground inside
 * each tower's LINZ footprint, split at the peaks of its height histogram, traced at 0.5 m and simplified 1 m; each
 * terrace's roof is its median. Facades: the use (OSM) and, per tower, tools/hero/sites/cbd_towers_style.json.
 * Sources: LINZ 2024 Auckland LiDAR and NZ Building Outlines (CC BY 4.0); © OpenStreetMap contributors (ODbL).
 */

/** podium: below 55 % of the top; shaft: the tower; crown: a small top level; plant: lift overruns and plant; spire: a mast. */
export type TowerPartKind = 'podium' | 'shaft' | 'crown' | 'plant' | 'spire';

/** Facade of a tower's shaft: curtain glass, ribbon windows between precast bands, punched windows, balconies. */
export type TowerFacade = 'glass' | 'bands' | 'punched' | 'balcony';

export interface TowerPrismPart {
  kind: Exclude<TowerPartKind, 'spire'>;
  /** Roof height above the ground (m); at the ring's centroid when sloped. */
  h: number;
  /** Roof slope (m/m) towards +x and +z (a wedge crown). */
  sx?: number;
  sz?: number;
  /** Footprint ring, flat [x0, z0, x1, z1, ...] (game m). */
  ring: readonly number[];
}

export interface TowerSpire {
  kind: 'spire';
  /** Tip above the ground (m) and the roof it stands on. */
  h: number;
  base: number;
  x: number;
  z: number;
}

export type TowerPart = TowerPrismPart | TowerSpire;

export interface CbdTower {
  /** Row of issue #156's table (tallest first). */
  n: number;
  tier: 'A' | 'B' | 'C' | 'C*';
  name: string;
  address: string;
  facade: TowerFacade;
  /** Shaft and podium colours (sRGB hex). */
  wall: number;
  podium: number;
  /** A lit crown (Tier A): the colour of the crown's facade at night. */
  crown?: 'lit';
  crownColour?: number;
  /** LiDAR spot checks [x, z, height above ground] (m, 3×3 median) inside the upper terraces. */
  spots: readonly (readonly number[])[];
  /** The LINZ footprints it replaces (union), flat ring (game m). */
  outline: readonly number[];
  /** A point inside each LINZ building it replaces (game m): the building whose first footprint holds one goes. */
  replaces: readonly (readonly number[])[];
  parts: readonly TowerPart[];
}

/** Side of the square spire / mast prism at its base (m) and the number of tapering steps. */
export const SPIRE_BASE = 3.2;
export const SPIRE_STEPS = 4;

/** A spire as stacked square prisms tapering to a point, flat rings and heights (the sim collides with them too). */
export function spirePrisms(s: TowerSpire): { h: number; ring: number[] }[] {
  const out: { h: number; ring: number[] }[] = [];
  for (let i = 0; i < SPIRE_STEPS; i++) {
    const r = (SPIRE_BASE / 2) * (1 - i / SPIRE_STEPS);
    const h = s.base + ((s.h - s.base) * (i + 1)) / SPIRE_STEPS;
    out.push({ h, ring: [s.x - r, s.z - r, s.x + r, s.z - r, s.x + r, s.z + r, s.x - r, s.z + r] });
  }
  return out;
}
