/**
 * F35-A — Auckland War Memorial Museum on the Domain (Pukekawa): the in-game model's shape, shared by
 * the scenery (world/scenery/museum.ts buildMuseum draws it) and the sim (a solid obstacle that
 * collapses when the player's jet flies into it, sim/buildings.ts).
 *
 * The shape is measured (core/museumData.ts, generated by tools/hero/sites/museum.py): the block's LiDAR
 * terraces in its OpenStreetMap outline, the Grand Atrium dome and the old central dome as nested LiDAR
 * contours, the portico's eight columns. The Domain itself is terrain: a jet that flies into the hill
 * crashes on the ground and the museum stands.
 */
import { MUSEUM_CENTRE, MUSEUM_COLUMNS, MUSEUM_PARTS } from './museumData';

export { MUSEUM_CENTRE, MUSEUM_COLUMNS, MUSEUM_OUTLINE, MUSEUM_PARTS, MUSEUM_SPOTS, type MuseumPartKind } from './museumData';

/** Where the game stands the museum (game x, z): its OSM outline's centroid. */
export const MUSEUM = { x: MUSEUM_CENTRE.x, z: MUSEUM_CENTRE.z } as const;

/** Its highest roof above the museum's ground (m): the top of the old central dome. */
export const MUSEUM_TOP = Math.max(...MUSEUM_PARTS.map((p) => p.h), ...MUSEUM_COLUMNS.map((c) => c[3]));

/**
 * The museum as the sim's prisms: a footprint ring (world XZ, flat) and the height of its top above
 * the ground. Every prism stands from the ground (the sim's buildings are prisms), so the domes' rings
 * are columns inside the block's. The portico's columns are 8-gons round the drawn 10-sided ones.
 */
export function museumSolids(): { ring: Float32Array; h: number }[] {
  const out = MUSEUM_PARTS.map((p) => ({ ring: Float32Array.from(p.ring), h: p.h }));
  const n = 8;
  for (const [x, z, r0, top] of MUSEUM_COLUMNS) {
    const r = r0 / Math.cos(Math.PI / n);
    const ring: number[] = [];
    for (let i = 0; i < n; i++) ring.push(x + Math.cos((i / n) * Math.PI * 2) * r, z + Math.sin((i / n) * Math.PI * 2) * r);
    out.push({ ring: Float32Array.from(ring), h: top });
  }
  return out;
}
