/**
 * F35-A — Auckland War Memorial Museum on the Domain (Pukekawa): the in-game model's shape, shared by
 * the scenery (world/scenery/museum.ts buildMuseum draws it) and the sim (a solid obstacle that
 * collapses when the player's jet flies into it, sim/buildings.ts).
 *
 * The shape is measured (core/museumData.ts, generated by tools/hero/sites/museum_bake.py from
 * tools/hero/sites/auckland_museum.py): the block's LiDAR terraces in its OpenStreetMap outline, the Grand Atrium
 * dome as its LiDAR surface, the north portico's entablature and eight columns. It is the top layer on the Auckland
 * Domain (core/aucklandDomain.ts), which keeps its trees and park buildings out of MUSEUM_OUTLINE. The Domain itself is
 * terrain: a jet that flies into the hill crashes on the ground and the museum stands.
 */
import { MUSEUM_CENTRE, MUSEUM_DOME, MUSEUM_PARTS, MUSEUM_PORTICO } from './museumData';

export { MUSEUM_CENTRE, MUSEUM_COLOURS, MUSEUM_DOME, MUSEUM_OUTLINE, MUSEUM_PARTS, MUSEUM_PORTICO, MUSEUM_SPOTS, type MuseumPartKind } from './museumData';

/** Where the game stands the museum (game x, z): its OSM outline's centroid. */
export const MUSEUM = { x: MUSEUM_CENTRE.x, z: MUSEUM_CENTRE.z } as const;

/** The portico's columns: [x, z, radius, top over the ground] (m); they carry the entablature. */
export const MUSEUM_COLUMNS: readonly (readonly [number, number, number, number])[] = MUSEUM_PORTICO.columns.map(([x, z, r]) => [x, z, r, MUSEUM_PORTICO.under] as const);

/** Its highest roof above the museum's ground (m): the top of the atrium dome. */
export const MUSEUM_TOP = Math.max(...MUSEUM_PARTS.map((p) => p.h), MUSEUM_DOME.top, MUSEUM_PORTICO.top);

/** The atrium dome's surface at grid point (i, j): its height over the ground (m), or null outside the dome. */
export function museumDomeAt(i: number, j: number): number | null {
  if (i < 0 || j < 0 || i >= MUSEUM_DOME.nx || j >= MUSEUM_DOME.nz) return null;
  const v = MUSEUM_DOME.h[j * MUSEUM_DOME.nx + i];
  return v < 0 ? null : v / 10;
}

/** World XZ of the dome's grid point (i, j). */
export function museumDomeXZ(i: number, j: number): [number, number] {
  const d = MUSEUM_DOME;
  return [d.origin[0] + i * d.ex[0] + j * d.ez[0], d.origin[1] + i * d.ex[1] + j * d.ez[1]];
}

/**
 * The museum as the sim's prisms: a footprint ring (world XZ, flat) and the height of its top above
 * the ground. Every prism stands from the ground (the sim's buildings are prisms): the terraces, the
 * dome's ring up to its top, the portico's entablature, and the columns as 8-gons round the drawn
 * 10-sided ones.
 */
export function museumSolids(): { ring: Float32Array; h: number }[] {
  const out = MUSEUM_PARTS.map((p) => ({ ring: Float32Array.from(p.ring), h: p.h }));
  out.push({ ring: Float32Array.from(MUSEUM_DOME.ring), h: MUSEUM_DOME.top });
  out.push({ ring: Float32Array.from(MUSEUM_PORTICO.ring), h: MUSEUM_PORTICO.top });
  const n = 8;
  for (const [x, z, r0, top] of MUSEUM_COLUMNS) {
    const r = r0 / Math.cos(Math.PI / n);
    const ring: number[] = [];
    for (let i = 0; i < n; i++) ring.push(x + Math.cos((i / n) * Math.PI * 2) * r, z + Math.sin((i / n) * Math.PI * 2) * r);
    out.push({ ring: Float32Array.from(ring), h: top });
  }
  return out;
}
