"""
F35-A — hero buildings: Eden Park (Ngā Ana Wai), the stands as the LiDAR sees them, for src/core/edenPark.ts (generated) —
#143 item 5 ("exists from OSM stands; check whether it needs more": it did — the stands stood as 26 m and 14 m office
blocks with flat roofs).

  python3 tools/hero/site.py --name eden_park --lat -36.87491 --lon 174.74469 --size 340 --res 0.3 --scale 40
  python3 tools/hero/osm.py --site /tmp/hero/eden_park
  python3 tools/hero/sites/eden_park.py --site /tmp/hero/eden_park          → src/core/edenPark.ts

Each OSM grandstand outline (ways 339478147 University of Auckland Stand, 339478152 Samsung Stand, 339478163 Kia
Stand, 339478164 West Stand) runs from the back of its roof down to the pitch, so the LiDAR surface over it is the
canopy, its cantilever and the open seating below it, 15–30 m at the back to about 1 m at the front, and not a plane (a
least-squares plane left 7–9 m RMS: the University stand's roof rises towards the pitch). So each stand is cut into eight
strips across its axis to the pitch (the axis: from its centroid to the stands' mean centroid), each strip at its median
height over the ground (at least 1.5 m): a profile along the axis, as the skill does for bridges. Spot checks: one LiDAR
cell in each strip's middle third, for tests/world-stadiums.test.ts.
Data: LINZ 2024 LiDAR (CC BY 4.0); © OpenStreetMap contributors (ODbL).
"""
import argparse, json, os, sys

import numpy as np
from shapely.geometry import Polygon

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..'))
sys.path.insert(0, HERE)
from heights import ring_mask  # noqa: E402
from cbd_towers import px_to_game  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--site', default='/tmp/hero/eden_park')
    ap.add_argument('--ts', default=os.path.join(HERE, '..', '..', '..', 'src', 'core', 'edenPark.ts'))
    a = ap.parse_args()
    d = np.load(f'{a.site}/lidar.npz')
    dsm, dem = d['dsm'], d['dem']
    box = [float(v) for v in d['box']]
    nd = dsm - dem
    feats = [f for f in json.load(open(f'{a.site}/osm.json'))['features'] if f['ring'] and f['tags'].get('building') == 'grandstand']
    centre = np.mean([Polygon(f['ring']).centroid.coords[0] for f in feats], 0)
    stands = []
    N = 8
    for f in feats:
        poly = Polygon(f['ring']).buffer(0)
        m = ring_mask(dem.shape, f['ring'])
        c = poly.centroid
        dv = centre - np.array([c.x, c.y])
        dv /= np.linalg.norm(dv)
        pv = np.array([-dv[1], dv[0]])
        ys, xs = np.where(m)
        t = (xs + 0.5 - c.x) * dv[0] + (ys + 0.5 - c.y) * dv[1]
        t0, t1 = float(t.min()), float(t.max()) + 1e-3
        strips = []
        for k in range(N):
            a0, a1 = t0 + (t1 - t0) * k / N, t0 + (t1 - t0) * (k + 1) / N
            # the strip: the outline between two lines across the stand's axis
            far = 1000
            band = Polygon([tuple(np.array([c.x, c.y]) + dv * a0 + pv * far), tuple(np.array([c.x, c.y]) + dv * a1 + pv * far),
                            tuple(np.array([c.x, c.y]) + dv * a1 - pv * far), tuple(np.array([c.x, c.y]) + dv * a0 - pv * far)])
            q = poly.intersection(band)
            if q.is_empty or q.area < 20:
                continue
            q = max(getattr(q, 'geoms', [q]), key=lambda g: g.area)
            cells = m & ring_mask(dem.shape, list(q.exterior.coords)[:-1])
            h = float(np.median(nd[cells])) if cells.sum() else 0.0
            # spot: the cell nearest the strip's centre (not chosen by its height: an independent check)
            sy, sx = np.where(cells)
            spot = None
            if len(sy):
                qc = q.centroid
                i = int(np.argmin((sx + 0.5 - qc.x) ** 2 + (sy + 0.5 - qc.y) ** 2))
                spot = [*[round(v, 1) for v in px_to_game(sx[i] + 0.5, sy[i] + 0.5, box)], round(float(nd[sy[i], sx[i]]), 1)]
            strips.append({'ring': [round(v, 2) for x, z in list(q.exterior.coords)[:-1] for v in px_to_game(x, z, box)],
                           'h': round(max(h, 1.5), 1), 'spot': spot})
        gx, gz = px_to_game(c.x, c.y, box)
        stands.append({'name': f['tags'].get('name', f['id']), 'x': round(gx, 1), 'z': round(gz, 1), 'strips': strips})
        print(stands[-1]['name'], [st['h'] for st in strips])
    lines = ['/**',
             ' * F35-A — GENERATED by tools/hero/sites/eden_park.py: Eden Park\'s four grandstands from the LINZ 2024 LiDAR inside',
             ' * their OpenStreetMap outlines, each cut into strips across its axis to the pitch, each strip at its median height',
             ' * (the canopy at the back, the cantilever, the seating raking down to the pitch). Heights over the ground (m).',
             ' * Matched to the OSM stands the scenery draws by centroid (world/scenery/aucklandSites.ts buildStadiums).',
             ' * Sources: LINZ 2024 LiDAR (CC BY 4.0); © OpenStreetMap contributors (ODbL). Do not edit by hand: rerun the recipe.',
             ' */',
             '',
             'export interface MeasuredStand {',
             '  name: string;',
             '  /** Centroid of the OSM outline (game m). */',
             '  x: number;',
             '  z: number;',
             '  /** Strips from the back to the pitch: ring (flat, game m), height over the ground (m), a LiDAR spot [x, z, h]. */',
             '  strips: readonly { ring: readonly number[]; h: number; spot: readonly number[] | null }[];',
             '}',
             '',
             'export const EDEN_PARK_STANDS: readonly MeasuredStand[] = [']
    for s_ in stands:
        lines.append(f"  {{ name: {json.dumps(s_['name'])}, x: {s_['x']}, z: {s_['z']}, strips: [")
        for st in s_['strips']:
            lines.append(f"    {{ h: {st['h']}, spot: {json.dumps(st['spot'])}, ring: [{', '.join(str(v) for v in st['ring'])}] }},")
        lines.append('  ] },')
    lines += ['];', '']
    open(a.ts, 'w').write('\n'.join(lines))


if __name__ == '__main__':
    main()
