"""
F35-A — hero buildings: port Westfield Newmarket's prototype model (tools/hero/sites/westfield_newmarket.py → model.json)
into the game as src/core/westfieldNewmarket.ts (generated) — #143 item 7.

  python3 tools/hero/sites/westfield_newmarket.py --site /tmp/hero/westfield_newmarket
  python3 tools/hero/sites/westfield_port.py --site /tmp/hero/westfield_newmarket          → src/core/westfieldNewmarket.ts

The model's local frame (metres, x = E − E0, z = N1 − N, heights over the mall's 2nd-percentile ground g0) becomes game
coordinates (NZTM → WGS84 → geoToWorld) and heights over the DEM at the mall's centroid, where the game stands it: the
game's terrain there is the ground, roofs are that plus the measured height. Prisms keep their wall material and their
plinth (base); the facade panels, the air bridge and the rotunda's dome come across as they are. The two "Westfield"
signs are not ported (the game draws no text on buildings yet).
Data: LINZ 2024 LiDAR (CC BY 4.0); © OpenStreetMap contributors (ODbL); Mapillary contributors (CC BY-SA 4.0, reference).
"""
import argparse, json, os, sys

import numpy as np
from shapely.geometry import Polygon
from shapely.ops import unary_union

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..'))
sys.path.insert(0, HERE)
from cbd_towers import px_to_game  # noqa: E402
from heights import ring_mask  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--site', default='/tmp/hero/westfield_newmarket')
    ap.add_argument('--ts', default=os.path.join(HERE, '..', '..', '..', 'src', 'core', 'westfieldNewmarket.ts'))
    a = ap.parse_args()
    S = a.site
    m = json.load(open(f'{S}/model.json'))
    d = np.load(f'{S}/lidar.npz')
    dem = d['dem']
    box = [float(v) for v in d['box']]
    feats = {f['id']: f for f in json.load(open(f'{S}/osm.json'))['features'] if f['ring']}
    mall = unary_union([Polygon(p['ring']).buffer(0) for p in m['prisms']])
    c = mall.centroid
    # g0 as the recipe has it; the game's ground is the DEM at the centroid, so heights shift by (DEM there − g0)
    mask = np.zeros_like(dem, dtype=bool)
    for p in m['prisms']:
        mask |= ring_mask(dem.shape, p['ring'])
    g0 = float(np.nanpercentile(dem[mask], 2))
    dg = float(np.median(dem[int(c.y) - 2:int(c.y) + 3, int(c.x) - 2:int(c.x) + 3])) - g0
    G = lambda x, z: [round(v, 2) for v in px_to_game(x, z, box)]  # noqa: E731
    ring = lambda r: [v for x, z in r for v in G(x, z)]  # noqa: E731
    H = lambda y: round(float(y) - dg, 2)  # noqa: E731
    cx, cz = G(c.x, c.y)
    out = ['/**',
           ' * F35-A — GENERATED by tools/hero/sites/westfield_port.py from the Westfield Newmarket prototype',
           ' * (tools/hero/sites/westfield_newmarket.py): OSM relation 11520833\'s parts at their LINZ 2024 LiDAR roof heights, walls',
           ' * from Mapillary street imagery, the Broadway frontage, the glass air bridge over Mortimer Pass and the 277 rotunda\'s',
           ' * dome. Heights (m) over the ground at the mall\'s centroid, where the game stands it. Do not edit by hand.',
           ' * Sources: LINZ 2024 LiDAR (CC BY 4.0); © OpenStreetMap contributors (ODbL); Mapillary contributors (CC BY-SA 4.0).',
           ' * Builder: world/scenery/westfieldNewmarket.ts.',
           ' */',
           '',
           "export type WestfieldMat = 'lattice' | 'precast_light' | 'precast_dark' | 'glass' | 'carpark' | 'slate' | 'shopfront' | 'metal' | 'glass_teal';",
           '',
           f'export const WESTFIELD_CENTRE = {{ x: {cx}, z: {cz} }};',
           '',
           '/** The mall\'s parts: ring (flat, game m), roof h over the ground, wall material, plinth {mat, h} (m up the wall). */',
           'export const WESTFIELD_PRISMS: readonly { id: string; ring: readonly number[]; h: number; wall: WestfieldMat; base?: { mat: WestfieldMat; h: number } }[] = [']
    for p in m['prisms']:
        base = f", base: {{ mat: '{p['base']['mat']}', h: {p['base']['h']} }}" if p.get('base') else ''
        out.append(f"  {{ id: '{p['id']}', h: {H(p['y1'])}, wall: '{p['wall']}'{base}, ring: [{', '.join(str(v) for v in ring(p['ring']))}] }},")
    out += ['];', '', '/** Facade panels on an edge: a → b (game m), y0..y1 over the ground, material. */',
            'export const WESTFIELD_FACADES: readonly { a: readonly number[]; b: readonly number[]; y0: number; y1: number; mat: WestfieldMat }[] = [']
    for f in m['facades']:
        out.append(f"  {{ a: {G(*f['a'])}, b: {G(*f['b'])}, y0: {H(f['y0'])}, y1: {H(f['y1'])}, mat: '{f['mat']}' }},")
    out += ['];', '', '/** The two-level glass air bridge over Mortimer Pass: from → to (game m), y0..y1, width (m). */']
    b = m['boxes'][0]
    out.append(f"export const WESTFIELD_BRIDGE = {{ from: {G(*b['from'])}, to: {G(*b['to'])}, y0: {H(b['y0'])}, y1: {H(b['y1'])}, width: {b['width']} }};")
    dm = m['domes'][0]
    out += ['', '/** The 277 rotunda\'s glass dome: centre (game m), springing height, radius, height / radius. */',
            f"export const WESTFIELD_DOME = {{ x: {G(dm['x'], dm['z'])[0]}, z: {G(dm['x'], dm['z'])[1]}, y: {H(dm['y'])}, r: {dm['r']}, squash: {dm['squash']} }};", '']
    # spot checks for the test: the DSM (3×3 median) at a point well inside each part, over the same ground
    dsm = d['dsm']
    spots = []
    for p in m['prisms']:
        if p['wall'] == 'glass':
            continue  # the LiDAR reads low through glass (the rotunda): its height is set, not measured
        q = Polygon(p['ring']).buffer(-4)
        if q.is_empty:
            continue
        # on a flat patch of roof (5×5 spread under 1 m) nearest the part's interior point, as the tower kit does:
        # a check of the model's roof, not of a ramp, a parked car or an edge
        from scipy import ndimage
        from shapely import contains_xy
        spread = ndimage.maximum_filter(dsm, 5) - ndimage.minimum_filter(dsm, 5)
        ys, xs = np.where(spread < 1.0)
        ok = contains_xy(q, xs + 0.5, ys + 0.5)
        if not ok.any():
            continue
        ys, xs = ys[ok], xs[ok]
        pt = q.representative_point()
        i = int(np.argmin((xs + 0.5 - pt.x) ** 2 + (ys + 0.5 - pt.y) ** 2))
        y, x = int(ys[i]), int(xs[i])
        v = float(np.median(dsm[y - 1:y + 2, x - 1:x + 2])) - g0
        spots.append([*G(x + 0.5, y + 0.5), H(v)])
    out += ['/** LiDAR spot checks [x, z, roof over the ground] (m, 3×3 median) inside each part. */',
            f'export const WESTFIELD_SPOTS: readonly (readonly number[])[] = {json.dumps(spots)};', '']
    open(a.ts, 'w').write('\n'.join(out))
    print('centre', cx, cz, 'dg', round(dg, 2), 'prisms', len(m['prisms']), 'facades', len(m['facades']), 'max h', max(H(p['y1']) for p in m['prisms']))


if __name__ == '__main__':
    main()
